import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Flex, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/layout/Foother";
import ProvidersTanstack from "@/context/ProvidersTanstack";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ProvidersTanstack>
          <Theme accentColor="violet" radius="small">
            <Flex direction={"column"} height={"100vh"}>
              {children}
              <Footer />
            </Flex>
          </Theme>
          </ProvidersTanstack>
        </body>
      </SessionProvider>
    </html>
  );
}
